### ISSUE TITLE
error Couldn't find any versions for "@factor/endpoint" that matches "^1.5.0"

### ISSUE THREAD

**Issue by bugknightyyp** [fictionco/fiction#174]
**Reason for this issue**
error Couldn't find any versions for "@factor/endpoint" that matches "^1.5.0"
**Steps to Reproduce**
just run `yarn create factor-app <project-name>`

**Comment by arpowers** [comment]
I just ran it with both 
```bash
npx create-factor-app
#and
yarn create factor-app
```

and didn't run into an issue. Are you using the latest version of LTS Node? Everything up to date?

**Comment by bugknightyyp** [comment]
@arpowers  
I use Mac, and here are the logs:
```log
➜  research node -v
v12.16.1
➜  research yarn -v
1.22.4
➜  research yarn create factor-app factor-demo
yarn create v1.22.4
warning package.json: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Installed "create-factor-app@1.5.0" with binaries:
      - create-factor-app
❯ Starting create-factor-app@1.5.0                                                                                                                                                                                                                                          22:57:55
                                                                                                                                                                                                                                                                            22:57:55
Great work!                                                                                                                                                                                                                                                                 22:57:55
✔ Generating Factor project in: /Users/yyp/research/factor-demo                                                                                                                                                                                                             22:57:55
                                                                                                                                                                                                                                                                            22:57:55
? Project name? factor-demo
warning ../../package.json: No license field
error Couldn't find any versions for "@factor/endpoint" that matches "^1.5.0"

yarn install v1.22.4
info No lockfile found.
[1/4] Resolving packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

/Users/yyp/.config/yarn/global/node_modules/sao/lib/installPackages.js:108
        throw new SAOError(`Failed to install ${packageName} in ${cwd}`)
        ^

SAOError: Failed to install packages in /Users/yyp/research/factor-demo
    at ChildProcess.<anonymous> (/Users/yyp/.config/yarn/global/node_modules/sao/lib/installPackages.js:108:15)
    at ChildProcess.emit (events.js:311:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:311:20)
    at Pipe.<anonymous> (net.js:668:12) {
  __sao: true
}
error Command failed.
Exit code: 1
Command: /usr/local/bin/create-factor-app
Arguments: factor-demo
Directory: /Users/yyp/research
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
➜  research 
```

**Comment by arpowers** [comment]
Well, it's showing version `1.5` here: 

https://www.npmjs.com/package/@factor/endpoint

The issue is for some reason your Yarn install isn't resolving the package?

**Comment by bugknightyyp** [comment]
try again now, it's ok.
