### ISSUE TITLE
Errors on initial build

### ISSUE THREAD

**Issue by chrisj74** [fictionco/fiction#192]
getting errors on initial build and unable to view pages in dashboard

**Steps to Reproduce**
Follow the setup instructions provided on install page.

- run `npx create-factor-app`
- provide name for project
- run `yarn factor dev`
- Follow onscreen instructions
- Select Zeno theme as part of setup

After build get the following error:
```
 ERROR  Server Rendering Error                                                                                                                                                                      20:32:22
 url:/

 ReferenceError: document is not defined

  at extendApp (webpack:///./node_modules/@factor/app/extend-app.ts?:43:19)

↑ Request / 0.060s Size: 0kb GET:500
↑ Request / 0.052s Size: 0kb GET:500
↑ Request /dashboard 0.047s Size: 0kb GET:200

 ERROR  Server Rendering Error                                                                                                                                                                      20:32:22
 url:/

 ReferenceError: document is not defined

  at extendApp (webpack:///./node_modules/@factor/app/extend-app.ts?:43:19) (repeated 0 times)


 ERROR  User token signature is invalid. The client user token does not match the token secret. You should only see this error once as client token will be cleared.                                20:32:24

↑ Request /_api_/posts → getSinglePost(loadUser) 0.008s Size: 0kb POST:200

 ERROR  Server Rendering Error                                                                                                                                                                      20:32:24
 url:/

 render function or template not defined in component: anonymous

  at normalizeRender (node_modules/vue-server-renderer/build.dev.js:8262:13)
  at renderComponentInner (node_modules/vue-server-renderer/build.dev.js:8412:3)
  at renderComponent (node_modules/vue-server-renderer/build.dev.js:8383:5)
  at RenderContext.renderNode (node_modules/vue-server-renderer/build.dev.js:8294:5)
  at RenderContext.next (node_modules/vue-server-renderer/build.dev.js:2598:23)
  at cachedWrite (node_modules/vue-server-renderer/build.dev.js:2451:9)
  at renderStringNode$1 (node_modules/vue-server-renderer/build.dev.js:8501:5)
  at RenderContext.renderNode (node_modules/vue-server-renderer/build.dev.js:8292:5)
  at RenderContext.next (node_modules/vue-server-renderer/build.dev.js:2598:23)
  at RenderContext.cachedWrite [as write] (node_modules/vue-server-renderer/build.dev.js:2451:9)
  at RenderContext.next (node_modules/vue-server-renderer/build.dev.js:2602:25)
  at RenderContext.cachedWrite [as write] (node_modules/vue-server-renderer/build.dev.js:2451:9)
  at RenderContext.next (node_modules/vue-server-renderer/build.dev.js:2602:25)
  at RenderContext.cachedWrite [as write] (node_modules/vue-server-renderer/build.dev.js:2451:9)
  at RenderContext.next (node_modules/vue-server-renderer/build.dev.js:2602:25)
  at RenderContext.cachedWrite [as write] (node_modules/vue-server-renderer/build.dev.js:2451:9)
  at RenderContext.next (node_modules/vue-server-renderer/build.dev.js:2602:25)
  at RenderContext.cachedWrite [as write] (node_modules/vue-server-renderer/build.dev.js:2451:9)
  at RenderContext.next (node_modules/vue-server-renderer/build.dev.js:2602:25)
  at RenderContext.cachedWrite [as write] (node_modules/vue-server-renderer/build.dev.js:2451:9)
  at RenderContext.next (node_modules/vue-server-renderer/build.dev.js:2602:25)
  at RenderContext.cachedWrite [as write] (node_modules/vue-server-renderer/build.dev.js:2451:9)

↑ Request / 0.019s Size: 0kb GET:500

 ERROR  Server Rendering Error                                                                                                                                                                      20:32:37
 url:/776f29d0657c5eb7a01d.hot-update.json

 render function or template not defined in component: anonymous

  at normalizeRender (node_modules/vue-server-renderer/build.dev.js:8262:13)
  at renderComponentInner (node_modules/vue-server-renderer/build.dev.js:8412:3)
  at renderComponent (node_modules/vue-server-renderer/build.dev.js:8383:5)
  at RenderContext.renderNode (node_modules/vue-server-renderer/build.dev.js:8294:5)
  at RenderContext.next (node_modules/vue-server-renderer/build.dev.js:2598:23)
  at cachedWrite (node_modules/vue-server-renderer/build.dev.js:2451:9)
  at renderStringNode$1 (node_modules/vue-server-renderer/build.dev.js:8501:5)
  at RenderContext.renderNode (node_modules/vue-server-renderer/build.dev.js:8292:5)
  at RenderContext.next (node_modules/vue-server-renderer/build.dev.js:2598:23)
  at RenderContext.cachedWrite [as write] (node_modules/vue-server-renderer/build.dev.js:2451:9)
  at RenderContext.next (node_modules/vue-server-renderer/build.dev.js:2602:25)
  at RenderContext.cachedWrite [as write] (node_modules/vue-server-renderer/build.dev.js:2451:9)
  at RenderContext.next (node_modules/vue-server-renderer/build.dev.js:2602:25)
  at RenderContext.cachedWrite [as write] (node_modules/vue-server-renderer/build.dev.js:2451:9)
  at RenderContext.next (node_modules/vue-server-renderer/build.dev.js:2602:25)
  at RenderContext.cachedWrite [as write] (node_modules/vue-server-renderer/build.dev.js:2451:9)
  at RenderContext.next (node_modules/vue-server-renderer/build.dev.js:2602:25)
  at RenderContext.cachedWrite [as write] (node_modules/vue-server-renderer/build.dev.js:2451:9)
  at RenderContext.next (node_modules/vue-server-renderer/build.dev.js:2602:25)
  at RenderContext.cachedWrite [as write] (node_modules/vue-server-renderer/build.dev.js:2451:9)
  at RenderContext.next (node_modules/vue-server-renderer/build.dev.js:2602:25)
  at RenderContext.cachedWrite [as write] (node_modules/vue-server-renderer/build.dev.js:2451:9)
```
Looking forward to using Factor as soon as I can get past this.

**Comment by arpowers** [comment]
@chrisj74 thanks for the bug report, this was fixed in the latest version.
