### ISSUE TITLE
No valid exports main found for

### ISSUE THREAD

**Issue by NuclleaR** [fictionco/fiction#202]
When I try to start new factor project I faced with issue

Steps to Reproduce
run in console
npx create-factor-app

❯ Starting create-factor-app@1.6.3                                                                                                                                                                  
Great work!                                                                                                                                                                                         
✔ Generating Factor project in: <my path>
 ERROR  No valid exports main found for '/Users/nuclear/.npm/_npx/24589/lib/node_modules/create-factor-app/node_modules/is-promise'
  at resolveExportsTarget (internal/modules/cjs/loader.js:625:9)
  at applyExports (internal/modules/cjs/loader.js:502:14)
  at resolveExports (internal/modules/cjs/loader.js:551:12)
  at Function.Module._findPath (internal/modules/cjs/loader.js:657:22)
  at Function.Module._resolveFilename (internal/modules/cjs/loader.js:960:27)
  at Function.Module._load (internal/modules/cjs/loader.js:855:27)
  at Module.require (internal/modules/cjs/loader.js:1033:19)
  at require (internal/modules/cjs/helpers.js:72:18)
  at Object.<anonymous> (/Users/nuclear/.npm/_npx/24589/lib/node_modules/create-factor-app/node_modules/run-async/index.js:3:17)
  at Module._compile (internal/modules/cjs/loader.js:1144:30)

node v13.6.0
npm v6.13.4

**Comment by arpowers** [comment]
Sounds like an install issue, delete `node_modules` and reinstall.
