### ISSUE TITLE
MongoDB has error at last release

### ISSUE THREAD

**Issue by andrewanswer** [fictionco/fiction#227]
**Reason for this issue**
$ npx factor start
██████████████████████████████████░░░░░░ 84% loaded(node:418406) UnhandledPromiseRejectionWarning: MongoError: Index key contains an illegal field name: field name starts with '$'.
    at Connection.<anonymous> (/home/andrewanswer/test/node_modules/mongodb/lib/core/connection/pool.js:451:61)
    at Connection.emit (events.js:314:20)
    at Connection.EventEmitter.emit (domain.js:486:12)
    at processMessage (/home/andrewanswer/test/node_modules/mongodb/lib/core/connection/connection.js:452:10)
    at Socket.<anonymous> (/home/andrewanswer/test/node_modules/mongodb/lib/core/connection/connection.js:621:15)
    at Socket.emit (events.js:314:20)
    at Socket.EventEmitter.emit (domain.js:486:12)
    at addChunk (_stream_readable.js:303:12)
    at readableAddChunk (_stream_readable.js:279:9)
    at Socket.Readable.push (_stream_readable.js:218:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:418406) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block)
                                                                                                                                                             09:47:14
Factor platform v1.8.25 (latest) / production mode

**Steps to Reproduce**
Just install fresh app without S3.

**Comment by andrewanswer** [comment]
Additional question - how to use local storage (w/o S3)?

**Comment by andrewanswer** [comment]
Resetting password procedure don't work on factor.dev site.

**Comment by pedroresende** [comment]
any news about this issue ? Just made a clean install and had exactly the same error
